project:
  type: website
  output-dir: docs

website:
  title: "Martin Habets, ECON PhD"
  description: "This is Martin Habets' personal website"
  favicon: "favicon.ico"
  page-footer:
    right: 
      - text: "Last updated: July, 2025"
  google-analytics: "G-4JM84VFV7T"
  
files:
  - robots.txt  
  - other/maps.html
  
format:
  html:
    email-obfuscation: javascript
    css: styles.css
    anchor-sections: false