project:
  type: website
  output-dir: docs

website:
  title: "Martin Habets"
  description: "This is Martin Habets' personal website."
  favicon: "favicon.ico"
  page-footer:
    right: 
      - text: "Last updated: April 26, 2024"
  google-analytics: "G-4JM84VFV7T"
  
format:
  html:
    email-obfuscation: javascript
    css: styles.css
    anchor-sections: false